In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

In [5]:
dataset = pd.read_csv('./data/Covid Data.csv')

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype 
---  ------                --------------    ----- 
 0   USMER                 1048575 non-null  int64 
 1   MEDICAL_UNIT          1048575 non-null  int64 
 2   SEX                   1048575 non-null  int64 
 3   PATIENT_TYPE          1048575 non-null  int64 
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64 
 6   PNEUMONIA             1048575 non-null  int64 
 7   AGE                   1048575 non-null  int64 
 8   PREGNANT              1048575 non-null  int64 
 9   DIABETES              1048575 non-null  int64 
 10  COPD                  1048575 non-null  int64 
 11  ASTHMA                1048575 non-null  int64 
 12  INMSUPR               1048575 non-null  int64 
 13  HIPERTENSION          1048575 non-null  int64 
 14  OTHER_DISEASE         1048575 non-null  int64 
 15

In [11]:
dataset["PATIENT_TYPE"].unique()

array([1, 2], dtype=int64)

In [12]:
dataset["INTUBED"].unique()

array([97,  1,  2, 99], dtype=int64)

In [13]:
dataset["PNEUMONIA"].unique()

array([ 1,  2, 99], dtype=int64)

In [17]:
dataset["ASTHMA"].unique()

array([ 2,  1, 98], dtype=int64)

In [21]:
dataset["CLASIFFICATION_FINAL"].unique()

array([3, 5, 7, 6, 1, 2, 4], dtype=int64)

In [18]:
class Person:
    def __init__(self, row):
        self.position = np.array([np.random.rand()*100, np.random.rand()*100])
        self.age = np.random.randint(18, 80)  # Asigna edades aleatorias
        self.sex = np.random.choice([1, 2])  # Asigna género aleatorio
        self.patient_type = np.random.choice([1,2])
        self.intubed = np.random.choice([1,2,99])
        self.pheumonia = np.random.choice([1,2,99])
        self.asthma = np.random.choice([1,2,98])

        # Inicialmente, nadie está infectado
        self.infected = False
        self.recovered = False
        self.days_infected = 0

        # Verifica si la persona está en el conjunto de pacientes con COVID-19
        if row['CLASIFFICATION_FINAL'] in [1,2,3]:
            self.infected = True


In [19]:
def distance(p1, p2):
    return np.linalg.norm(p1.position - p2.position)

In [20]:
# Crear la población
people = [Person(row) for _, row in dataset.iterrows()]

# Definir parámetros de la simulación
num_days = 100
infection_radius = 5  # Ajusta según sea necesario
infection_prob = 0.2  # Ajusta según sea necesario
mortality_rate = 0.03  # Ajusta según sea necesario

# Simular la propagación del virus
list_images = []

KeyboardInterrupt: 

In [ ]:
for day in range(num_days):
    infected_people = [person for person in people if person.infected and not person.recovered]

    for person in people:
        if person.infected and not person.recovered:
            for other in people:
                if not other.infected and not other.recovered and distance(person, other) < infection_radius:
                    if np.random.rand() < infection_prob:
                        other.infected = True

            # Simular la recuperación o muerte después de ciertos días
            person.days_infected += 1
            if person.days_infected >= np.random.randint(7, 14):  # Ajusta según sea necesario
                if np.random.rand() < mortality_rate:
                    person.recovered = False
                    person.infected = False
                else:
                    person.recovered = True

    # Graficar usando la lista de colores y marcadores
    x_infected = [person.position[0] for person in infected_people]
    y_infected = [person.position[1] for person in infected_people]
    x_recovered = [person.position[0] for person in people if person.recovered]
    y_recovered = [person.position[1] for person in people if person.recovered]
    x_not_infected = [person.position[0] for person in people if not person.infected]
    y_not_infected = [person.position[1] for person in people if not person.infected]

    plt.plot(x_not_infected, y_not_infected, 'bo', label='Not Infected')
    plt.plot(x_infected, y_infected, 'ro', label='Infected')
    plt.plot(x_recovered, y_recovered, 'go', label='Recovered')
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Day "+str(day))
    plt.legend()
    name = "day_"+str(day)+".jpg"
    plt.savefig(name, format="jpg")
    plt.close()
    list_images.append(name)

In [ ]:
images = [Image.open(path) for path in list_images]

# Guardar las imágenes como un GIF animado
gif_path = "covid_simulation.gif"
images[0].save(gif_path, save_all=True, append_images=images[1:], loop=0, duration=400)

# Mostrar el GIF animado
display(IPImage(filename=gif_path))